---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigcp-everis
spec:
  selector:
    matchLabels:
      app: apigcp-everis
  replicas: 1
  template:
    metadata:
      labels:
        app: apigcp-everis
    spec:
      containers:
      - name: apigcp-everis
        image: gcr.io/true-server-269807/apigcp:latest
        #imagePullPolicy: Never
        ports:
        - containerPort: 4000