pipeline {
  agent{
    node {
      label 'master'
    }
  }
 
  stages {
 
	  stage('Initialize'){
	    steps{
		    script{
			  def dockerHome = tool 'myDocker'
			  env.PATH = "${dockerHome}/bin:${env.PATH}"
		  }
	    }
	  }
	
    //stage('test') {
	  //  agent { docker { image 'python:3' } }
    //  steps {
    //    sh 'python3 ${WORKSPACE}/src/test.py'
    //  }
    //}

    stage('Docker Login'){
      environment {
        DOCKER_CREDENTIALS = credentials('docker-repo-login')
      }
      steps{
        sh 'docker login -u ${DOCKER_CREDENTIALS_USR} -p ${DOCKER_CREDENTIALS_PSW}'
      }
    }
	
    stage('Docker Image build and tag') {
      steps{
	      sh 'docker build -t cchanta/tecamia-devops:v1.0 -f ${WORKSPACE}/dockerfile'
        sh 'docker push cchanta/tecamia-devops:v1.0'
		  }
    }
  }
}